### ISSUE TITLE
愿意把SM2带到 shadowsocks/crypto2 密码库里面来吗？

### ISSUE THREAD

**Issue by LuoZijun** [Pencil-Yao/efficient-sm2#2]
Hi, `crypto2` 库是目前银河系最快的密码库，请问你愿意把SM2带到 [shadowsocks/crypto2](https://github.com/shadowsocks/crypto2) 密码库里面来吗？

`crypto2` 的 bench 数据： https://github.com/LuoZijun/crypto-bench

**Comment by Pencil-Yao** [comment]
这听起来不错

**Comment by Pencil-Yao** [comment]
我有两个问题：
1. 根据 readme 你们的今后 `crypto2` 只支持 `sm2` 一条椭圆曲线吗
2.  es2 以什么样的形式添加到 `crypto2`

**Comment by LuoZijun** [comment]
@Pencil-Yao 

> 1. 根据 readme 你们的今后 crypto2 只支持 sm2 一条椭圆曲线吗

大概就是我自己本人没有兴趣实现（也没有项目需求），PR 还是乐于接受的。

> 2. es2 (sm2) 以什么样的形式添加到 crypto2

我想直接添加代码进去会更好？

**Comment by Pencil-Yao** [comment]
> @Pencil-Yao
> 
> > 1. 根据 readme 你们的今后 crypto2 只支持 sm2 一条椭圆曲线吗
> 
> 大概就是我自己本人没有兴趣实现（也没有项目需求），PR 还是乐于接受的。
> 
> > 1. es2 (sm2) 以什么样的形式添加到 crypto2
> 
> 我想直接添加代码进去会更好？

ok 那就 submodule 的形式添加进去好了 方便后期维护

**Comment by LuoZijun** [comment]
@Pencil-Yao 

> ok 那就 submodule 的形式添加进去好了 方便后期维护

额，我更希望是代码可以直接放到 `crypto2/src/` 里面去。同时我看到了你的依赖里面有个 `libsm` ，这个应该是放在 `dev-dep` 里面吧 :)

**Comment by LuoZijun** [comment]
@Pencil-Yao 另外，我初步看了当前的代码，我觉得还需要一段时间的打磨。不过作为一个开始，已经很不错了 :)

**Comment by Pencil-Yao** [comment]
> @Pencil-Yao 另外，我初步看了当前的代码，我觉得还需要一段时间的打磨。不过作为一个开始，已经很不错了 :)

ty
